version: '3.8'
services:
  app:
    build: .
    container_name: streamlit_bot
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8501:8501"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
